
#   docker compose -f docker-compose.dev.yml down
#   docker compose -f docker-compose.dev.yml up -d

name: trellis-dev
services:
  db:
    image: postgres:18
    container_name: trellis-dev-db
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - trellis_postgres_dev_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U trellis -d trellisdb" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  trellis_postgres_dev_data: